apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
spec:
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 11.6.5
    helm:
      values: |
        tls:
          enabled: true
